// gradle/versions.gradle.kts
extra["jfrogVersion"] = "4.29.1"
extra["mavenGradleVersion"] = "2.1"
extra["androidxAppcompatVersion"] = "1.5.1"
extra["androidxConstraintLayoutVersion"] = "2.1.4"
extra["androidxLifecycleExtensionsVersion"] = "2.2.0"
extra["androidxRecyclerViewVersion"] = "1.2.1"
extra["androidxMultidexVersion"] = "2.0.1"
extra["androidxAnnotation"] = "1.2.0"
extra["materialVersion"] = "1.7.0"
extra["playAuthVersion"] = "17.0.0"
extra["playMapsVersion"] = "17.0.0"
extra["playLocationVersion"] = "17.0.0"
extra["firebaseUiVersion"] = "7.1.1"

extra["firebaseBOM"] = "30.1.0"

// Unused Firebase versions commented out
// extra["firebaseCoreVersion"] = "17.4.1"
// extra["firebaseDatabaseVersion"] = "19.6.0"
// extra["firebaseFirestoreVersion"] = "22.0.1"
// extra["firebaseAuthVersion"] = "20.0.1"
// extra["firebaseStorageVersion"] = "19.2.1"
// extra["firebaseMessagingVersion"] = "23.0.6"
// extra["firebaseFunctionsVersion"] = "19.2.0"
// extra["firebasePerformanceVersion"] = "19.1.1"
// extra["firebaseCrashlyticsVersion"] = "17.3.1"
// extra["firebaseAnalyticsVersion"] = "18.0.0"

extra["greenDaoVersion"] = "3.3.0"
extra["frescoVersion"] = "1.13.0"
extra["rxJavaVersion"] = "2.2.17"
extra["rxAndroidVersion"] = "2.1.1"
extra["rxRelayVersion"] = "2.1.1"
extra["rxQueueVersion"] = "2.0.0"
extra["compressorVersion"] = "2.1.1"
extra["okHttpVersion"] = "4.10.0"
// extra["okHttpVersion"] = "3.12.1"
extra["okHttpDownloaderVersion"] = "1.1.0"
extra["prettyTimeVersion"] = "4.0.4.Final"
extra["imageCropperVersion"] = "2.9.0"
extra["photoViewVersion"] = "2.3.0"
extra["androidDatabaseSQLCipher"] = "4.3.0"
extra["chatKitVersion"] = "0.3.6"
extra["circleImageViewVersion"] = "3.1.0"
extra["dexterVersion"] = "6.2.3"
extra["tinyLogVersion"] = "1.3.6"

extra["materialDrawerVersion"] = "8.2.0"

extra["iconicsVersion"] = "5.3.3"
extra["iconicsGoogleMaterialIconsVersion"] = "4.0.0.2-kotlin@aar"
extra["iconicsFontAwesomeTypefaceVersion"] = "5.9.0.2-kotlin@aar"

extra["materialSearchVersion"] = "1.5.0"
extra["materialSpinnerVersion"] = "1.3.1"
extra["keyboardVisibilityEventVersion"] = "3.0.0-RC2"
// extra["androidAudioRecorderVersion"] = "0.3.9"
extra["androidAudioRecorderVersion"] = "1.0.0"
extra["glideVersion"] = "4.13.0"
extra["exoplayerVersion"] = "2.18.2"
extra["androidAudioConverterVersion"] = "0.0.8"
extra["gsonVersion"] = "2.8.8"

extra["qrGenerator"] = "1.1.0"
extra["zxing"] = "2.0"

// Used by file messages
extra["androidNetworkingVersion"] = "v1.0.2"
extra["pdfiumVersion"] = "1.9.0"

extra["smackVersion"] = "4.4.5"
extra["activity_ktx_version"] = "1.2.3"

extra["kotlin_version"] = "1.6.10"
extra["kotlin_version_jdk7"] = "1.6.10"
extra["activityKtxVersion"] = "1.6.1"
extra["fragmentKtxVersion"] = "1.5.5"